config/routes.rb
Index::Application.routes.draw do
  resources :divisions do
    collection do
      get :show_workers
    end
  end

  resources :factor_descriptions

  resources :directions do
    collection do
      get :show_eigen_blocks, :show_eigen_subblocks, :show_eigen_factors, :show_articles
    end
  end

  resources :blocks
  resources :subblocks
  resources :factors do
    collection do
      get :new_factor, :edit_weights
      post :save_weights, :save_updated_weights
    end
  end

  resources :ratings do
    collection do
      get :get_rating_params, :show_rating, :show_indexes, :get_calc_params, :calc_rating, :show_index_changes, :show_value_changes, :show_factor_chart, :show_index_chart
    end
  end

  root :to => "divisions#index"

end

app/models/block.rb
class Block < ActiveRecord::Base
  belongs_to :direction, :foreign_key => 'scope_id'
  has_many :subblocks, :foreign_key => 'group_id'
  has_many :ratings, :foreign_key => 'group_id'
  set_table_name "groups"
end

app/controllers/blocks_controller.rb
# coding: utf-8
class BlocksController < ApplicationController
#  before_filter :find_block, :only => [:show, :edit, :update, :destroy]
#  before_filter :find_direction, :only => [:new_block, :edit_weights]
  before_filter :find_direction, :only => [:new, :create]
#  before_filter :find_blocks, :only => [:new_block, :edit_weights]
  def index
    @blocks = Block.all
  end
  
  def show
  end

  def new_block
    @block = Block.new
  end

  def new
    @block = Block.new
  end
  
  def create
#    @block = Block.new params[:block]
    @block = @direction.blocks.build(params[:block])
    if not @block.save
      render :new
    else
      redirect_to :controller => 'directions', :action => 'show_eigen_blocks', :id => params[:direction_id]
    end
  end
  
  def save_weights
    total_weight = 0
    if params[:w]
      params[:w].keys.each  do |id|
        total_weight += params[:w][id.to_s][:weight].to_f
      end
    end  
    total_weight += params[:new_block][:weight].to_f
    if total_weight>1
      flash_error :weight_is_wrong
      redirect_to :action => 'new_block', :direction_id => params[:direction_id]
    else 
      @blocks = Block.where("direction_id=?",  params[:direction_id])
      if @blocks.size>0
        @blocks.collect { |b|
          @block_weight = BlockWeight.new
          @block_weight.block_id = b.id
          @block_weight.start_date = Time.now
          @block_weight.weight = params[:w][b.id.to_s][:weight]
          @block_weight.description = params[:new_block][:description]
          @block_weight.save
        }
      end
      @block = Block.new
      @block.direction_id = params[:direction_id]
      @block.block_description_id = params[:new_block][:block_description_id]
      @block.save
      @block_weight = BlockWeight.new
      @block_weight.block_id = @block.id
      @block_weight.weight = params[:new_block][:weight]
      @block_weight.start_date = Time.now
      @block_weight.description = params[:new_block][:description]
      @block_weight.save
      redirect_to :controller => 'directions', :action => 'show_eigen_blocks', :id => params[:direction_id]
    end
  end
  
  def edit_weights
  end

  def save_updated_weights
    total_weight = 0
    params[:w].keys.each  do |id|
      total_weight += params[:w][id.to_s][:weight].to_f
    end
    if total_weight>1
      flash_error :weight_is_wrong
      redirect_to :action => 'edit_weights', :direction_id => params[:direction_id]
    else 
      @blocks = Block.where("direction_id=?",  params[:direction_id])
      if @blocks.size>0
        @blocks.collect { |b|
          @block_weight = BlockWeight.new
          @block_weight.block_id = b.id
          @block_weight.start_date = Time.now
          @block_weight.weight = params[:w][b.id.to_s][:weight]
          @block_weight.description = params[:w][b.id.to_s][:description]
          @block_weight.save
        }
      end
      redirect_to :controller => 'directions', :action => 'show_eigen_blocks', :id => params[:direction_id]
    end
  end
  
  def update
    if not @block.update_attributes params[:block]
      render :action => :edit
    else
      redirect_to block_path(@block)
    end
  end
  
  def destroy
    @block.destroy
    redirect_to blocks_path
  end
  private
  
  def find_block
    if params[:id]
      @block = Block.find params[:id]
    else
      @block = Block.find params[:block][:id]
    end
  end
  
  def find_direction
    @direction = Direction.find params[:direction_id]  
  end
  
  def find_blocks
    @blocks = Block.where("direction_id=?",  params[:direction_id])
  end
end

app/views/blocks/_form.html.haml
%h1
  = submit
  блок показателей
.content
  - form_for @block do |form|
    %table.card
      %tr
        %th Полное название
        %td= form.text_field :name
      %tr
        %th Сокращенное название
        %td= form.text_field :short_name
      -#%tr
        -#%th Вес
        -#%td= form.text_field :weight
    %br
  
    = submit_tag submit

app/views/blocks/edit.html.haml
= render :partial => 'form', :locals => { :submit => 'Редактировать' }

app/views/blocks/edit_weights.html.haml
%h1 Изменение весов блоков для шаблона "#{@direction.name}"
%h4 Примечание: сумма весов всех блоков должна равняться 1
.content
  - form_for 'blocks[]', :d, :url => {:action => 'save_updated_weights', :direction_id => @direction} do |form|
    %table.data
      %tr
        %th Название
        %th Вес
        %th Описание
      - for @b in @blocks
        %tr
          %td= @b.block_description.short_name
          - @w = @b.block_weights.last
          %td= text_field :w, :weight, :index => @b.id, :size => 4
          %td= text_field :w, :description, :index => @b.id, :size => 50
      %br
    = submit_tag "Сохранить"
    

app/views/blocks/index.html.haml
# coding: utf-8
%h1 Блоки показателей 

.content
  %table.data
    %tr
      %th Название
      %th Вес
    - for b in @blocks
      %tr
        %td= link_to b.name, :action => 'show', :id => b 
        %td= b.weight
-#        %td= link_to 'Показатели', factors_path(b.id)
-#%br	
-#.actions
  -#= link_to 'Добавить', :action => 'new'

app/views/blocks/new.html.haml
%h1 Новая группа направления "#{@direction.name}"
.content
  - form_for @block, :url => {:action => "create", :direction_id => @direction} do |form|
    %table.card
      %tr
        %th Название
        %td= form.text_field :name
      %br
    = submit_tag "Сохранить"

app/views/blocks/new_block.html.haml
%h1 Новый блок показателей шаблона "#{@direction.name}"
%h4 Примечание: сумма весов всех блоков должна равняться 1
.content
  - form_for 'blocks[]', :d, :url => {:action => 'save_weights', :direction_id => @direction} do |form|
    %table.data
      %tr
        %th Название
        %th Вес
        %th Описание
      - for @b in @blocks
        %tr
          %td= @b.block_description.short_name
          - @w = @b.block_weights.last
          %td= text_field :w, :weight, :index => @b.id, :size => 4
          %td= @w.description
      %tr
        %td= select :new_block, :block_description_id, BlockDescription.all.collect {|bd| [ bd.short_name, bd.id ] }
        %td= text_field :new_block, :weight, :size => 4
        %td= text_field :new_block, :description, :size => 50 
      %br
    = submit_tag "Сохранить"
    

app/views/blocks/show.html.haml
# coding: utf-8
%h1 Описание блока "#{@block.name}" 

.content
  %table.data
    %tr
      %th Полное название:
      %td= @block.name
    %tr
      %th Сокращенное название:
      %td= @block.short_name
    %tr
      %th Вес:
      %td= @block.weight
%br      
.actions
  = link_to 'Редактировать', edit_block_path(@block)
  -#= link_to 'Удалить', block_path(@block), :method => :delete, :confirm => "Удалить описание блока?"